# Site settings
title: Dadams solutions
description: "Dadams, solutions, custom software, programmer, coder"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dadams.solutions" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - .dockerignore
  - README.md
